= bespoke-extern
Dan Allen <https://github.com/mojavelinux>
// Settings:
:idprefix:
:idseparator: -
//ifdef::env-github[:badges:]
// Variables:
:release-version: master
// URIs:
:uri-raw-file-base: https://raw.githubusercontent.com/opendevise/bespoke-extern/{release-version}

ifdef::badges[]
image:https://img.shields.io/npm/v/bespoke-extern.svg[npm package, link=https://www.npmjs.com/package/bespoke-extern]
image:https://img.shields.io/travis/opendevise/bespoke-extern/master.svg[Build Status (Travis CI), link=https://travis-ci.org/opendevise/bespoke-extern]
endif::[]

Exports the Bespoke.js API to a global variable named `bespoke` and provides access to the collection of deck instances via `bespoke.decks` and the most recent deck via `bespoke.deck`.

This plugin is designed to give access to tools that need to control the deck, such as presentation exporters like deck2pdf and decktape.

== Example

//http://opendevise.github.io/bespoke-extern[View the demo] online.

This repository includes a demo folder the shows this plugin in action.
To view it locally, you first need to clone this repository:

 $ git clone https://github.com/opendevise/bespoke-extern && cd bespoke-extern

Next, install the dependencies inside the project folder using npm:

 $ npm install

Finally, visit the file [path]_demo/index.html_ in your browser to see the plugin in action.

== Download

Download the {uri-raw-file-base}/dist/bespoke-extern.min.js[production mode version] or the {uri-raw-file-base}/dist/bespoke-extern.js[development mode version], or use a package manager.

=== npm

 $ npm install bespoke-extern

=== Bower

 $ bower install bespoke-extern

== Usage

This plugin is shipped in a https://github.com/umdjs/umd[UMD format], meaning it is available as a CommonJS/AMD module or as a browser global.

For example, when using CommonJS modules:

```js
var bespoke = require('bespoke'),
  extern = require('bespoke-extern');

bespoke.from('.deck', [
  extern(bespoke)
]);
```

When using a browser global:

```js
bespoke.from('.deck', [
  bespoke.plugins.extern()
]);
```

== License

http://en.wikipedia.org/wiki/MIT_License[MIT License]
